server:
  port: 8082

spring:
  application:
    name: banking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bankingdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  banking:
    step-up-threshold: 1000.00

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8080}   # added
    internal-token: ${INTERNAL_SERVICE_TOKEN:}

jwt:
  secret: ${JWT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.passwordlessauth.banking: INFO
